export const BANNER_REQUEST = 'BANNER_REQUEST'
export const BANNER_SUCCESS = 'BANNER_SUCCESS'
export const BANNER_ERROR = 'BANNER_ERROR'

export const CREATE_BANNER_REQUEST = 'CREATE_BANNER_REQUEST'
export const CREATE_BANNER_SUCCESS = 'CREATE_BANNER_SUCCESS'
export const CREATE_BANNER_ERROR = 'CREATE_BANNER_ERROR'

export const UPDATE_BANNER_REQUEST = 'UPDATE_BANNER_REQUEST'
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS'
export const UPDATE_BANNER_ERROR = 'UPDATE_BANNER_ERROR'

export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST'
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS'
export const DELETE_BANNER_ERROR = 'DELETE_BANNER_ERROR'
