export const BLOCK_REQUEST = 'BLOCK_REQUEST'
export const BLOCK_SUCCESS = 'BLOCK_SUCCESS'
export const BLOCK_ERROR = 'BLOCK_ERROR'

export const BLOCKS_REQUEST = 'BLOCKS_REQUEST'
export const BLOCKS_SUCCESS = 'BLOCKS_SUCCESS'
export const BLOCKS_ERROR = 'BLOCKS_ERROR'

export const CREATE_BLOCK_REQUEST = 'CREATE_BLOCK_REQUEST'
export const CREATE_BLOCK_SUCCESS = 'CREATE_BLOCK_SUCCESS'
export const CREATE_BLOCK_ERROR = 'CREATE_BLOCK_ERROR'

export const UPDATE_BLOCK_REQUEST = 'UPDATE_BLOCK_REQUEST'
export const UPDATE_BLOCK_SUCCESS = 'UPDATE_BLOCK_SUCCESS'
export const UPDATE_BLOCK_ERROR = 'UPDATE_BLOCK_ERROR'

export const DELETE_BLOCK_REQUEST = 'DELETE_BLOCK_REQUEST'
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS'
export const DELETE_BLOCK_ERROR = 'DELETE_BLOCK_ERROR'
