export const SELECT_IMAGE = 'SELECT_IMAGE'

export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR'
