export const IMPORT_VIRTUAL_CARDS_REQUEST = 'IMPORT_VIRTUAL_CARDS_REQUEST'
export const IMPORT_VIRTUAL_CARDS_SUCCESS = 'IMPORT_VIRTUAL_CARDS_SUCCESS'
export const IMPORT_VIRTUAL_CARDS_ERROR = 'IMPORT_VIRTUAL_CARDS_ERROR'
