export const REGIONS_REQUEST = 'REGIONS_REQUEST'
export const REGIONS_SUCCESS = 'REGIONS_SUCCESS'
export const REGIONS_ERROR = 'REGIONS_ERROR'

export const STORES_REQUEST = 'STORES_REQUEST'
export const STORES_SUCCESS = 'STORES_SUCCESS'
export const STORES_ERROR = 'STORES_ERROR'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const SELECT_REGION = 'SELECT_REGION'
export const SELECT_STORE = 'SELECT_STORE'
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS'

export const DISCOUNT_UPLOAD_REQUEST = 'DISCOUNT_UPLOAD_REQUEST'
export const DISCOUNT_UPLOAD_SUCCESS = 'DISCOUNT_UPLOAD_SUCCESS'
export const DISCOUNT_UPLOAD_ERROR = 'DISCOUNT_UPLOAD_ERROR'

export const IMPORT_VIRTUAL_CARDS_REQUEST = 'IMPORT_VIRTUAL_CARDS_REQUEST'
export const IMPORT_VIRTUAL_CARDS_SUCCESS = 'IMPORT_VIRTUAL_CARDS_SUCCESS'
export const IMPORT_VIRTUAL_CARDS_ERROR = 'IMPORT_VIRTUAL_CARDS_ERROR'
