export const REGIONS_REQUEST = 'REGIONS_REQUEST'
export const REGIONS_SUCCESS = 'REGIONS_SUCCESS'
export const REGIONS_ERROR = 'REGIONS_ERROR'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR'
